Update prod.yml

diff --git a/.github/workflows/prod.yml b/.github/workflows/prod.yml
--- a/.github/workflows/prod.yml
+++ b/.github/workflows/prod.yml
@@ -10,7 +10,7 @@ jobs:
     runs-on: bpProd-runner
     defaults:
       run:
-        working-directory: /var/www/aihomework/boilerplate/prod
+        working-directory: /var/www/aihomework/boilerplate
 
     steps:
       - name: Checkout code
@@ -28,22 +28,22 @@ jobs:
         run: |
             git remote rm action
 
-      - name: Stash or remove local changes
-        run: |
-            if git diff --quiet; then
-              echo "No local changes to stash."
-            else
-              echo "Stashing local changes..."
-              git stash --include-untracked || echo "Failed to stash changes. Attempting to reset..."
-              git reset --hard || exit 1
-            fi
+      # - name: Stash or remove local changes
+      #   run: |
+      #       if git diff --quiet; then
+      #         echo "No local changes to stash."
+      #       else
+      #         echo "Stashing local changes..."
+      #         git stash --include-untracked || echo "Failed to stash changes. Attempting to reset..."
+      #         git reset --hard || exit 1
+      #       fi
 
       - name: Pull from GitHub
         id: pull
         run: |
             remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
-            git remote add action $remote_repo
-            git pull $remote_repo main
+            # git remote add action $remote_repo
+            git clone $remote_repo main
 
       - name: Install dependencies
         run: yarn install --frozen-lockfile
@@ -62,15 +62,15 @@ jobs:
 
       - name: Setup and restart service
         run: |
-          sudo cp server-script/aihomeworkprod.service /etc/systemd/system
+          sudo cp server-script/aihomeworkmain.service /etc/systemd/system
           sudo systemctl daemon-reload
-          sudo systemctl restart aihomeworkprod.service
+          sudo systemctl restart aihomeworkmain.service
 
       - name: Verify deployment
         run: |
           echo "Waiting for service to start..."
           sleep 10
-          if sudo systemctl is-active --quiet aihomeworkprod.service; then
+          if sudo systemctl is-active --quiet aihomeworkmain.service; then
             echo "Deployment successful!"
           else
             echo "Deployment failed!"
